'use strict';

function Board(pieces) {

  var NO_PIECE = pieces.NO_PIECE;

  this.board =
    {
      'a8': {'piece': pieces.WR, 'isSelected': false},
      'b8': {'piece': pieces.WN, 'isSelected': false},
      'c8': {'piece': pieces.WB, 'isSelected': false},
      'd8': {'piece': pieces.WQ, 'isSelected': false},
      'e8': {'piece': pieces.WK, 'isSelected': false},
      'f8': {'piece': pieces.WB, 'isSelected': false},
      'g8': {'piece': pieces.WN, 'isSelected': false},
      'h8': {'piece': pieces.WR, 'isSelected': false},
      'a7': {'piece': pieces.WP, 'isSelected': false},
      'b7': {'piece': pieces.WP, 'isSelected': false},
      'c7': {'piece': pieces.WP, 'isSelected': false},
      'd7': {'piece': pieces.WP, 'isSelected': false},
      'e7': {'piece': pieces.WP, 'isSelected': false},
      'f7': {'piece': pieces.WP, 'isSelected': false},
      'g7': {'piece': pieces.WP, 'isSelected': false},
      'h7': {'piece': pieces.WP, 'isSelected': false},
      'a6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'b6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'c6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'f6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'g6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'h6': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'a5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'b5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'c5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'f5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'g5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'h5': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'a4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'b4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'c4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'f4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'g4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'h4': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'a3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'b3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'c3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'd3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'e3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'f3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'g3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'h3': {'piece': pieces.NO_PIECE, 'isSelected': false},
      'a2': {'piece': pieces.BP, 'isSelected': false},
      'b2': {'piece': pieces.BP, 'isSelected': false},
      'c2': {'piece': pieces.BP, 'isSelected': false},
      'd2': {'piece': pieces.BP, 'isSelected': false},
      'e2': {'piece': pieces.BP, 'isSelected': false},
      'f2': {'piece': pieces.BP, 'isSelected': false},
      'g2': {'piece': pieces.BP, 'isSelected': false},
      'h2': {'piece': pieces.BP, 'isSelected': false},
      'a1': {'piece': pieces.BR, 'isSelected': false},
      'b1': {'piece': pieces.BN, 'isSelected': false},
      'c1': {'piece': pieces.BB, 'isSelected': false},
      'd1': {'piece': pieces.BQ, 'isSelected': false},
      'e1': {'piece': pieces.BK, 'isSelected': false},
      'f1': {'piece': pieces.BB, 'isSelected': false},
      'g1': {'piece': pieces.BN, 'isSelected': false},
      'h1': {'piece': pieces.BR, 'isSelected': false}
    };
}

chess.factory('Board', function() {
  return Board;
})
